[Google]
type = drive
scope = drive
token = {"access_token":"ya29.a0AZYkNZgD-M5L14kAQzGYrHS0GBkwgSgWGX0fCj3lK5h-dXmP2LasD28cXWZ8kFPN9wHnxGpUPH2EXuB_qIAESJvVhgC9HbvGn5wLALIw4FMimVujHliE3d3VQfWNYVk16-rV7VykcvPE47wKaKmfUJn4Hhb1na6MMoRKX2aEaCgYKAfYSARQSFQHGX2Mi5E116-WUJM1g1IMary02ow0175","token_type":"Bearer","refresh_token":"1//0582XSOpubOGCCgYIARAAGAUSNwF-L9IrTU1fxQiklzq13XIA_uhpThFcCpE9ewBLdogOZvI4heJM8KmF2CD-EK27JcuQfIGBuy8","expiry":"2025-05-05T12:23:38.720693491-04:00"}
